### ISSUE TITLE
No more tests from GitHub action on commits?

### ISSUE THREAD

**Issue by jerabaul29** [ddclient/ddclient#384]
I see that there are no more 'green ticks' indicating successful GitHub action CI. Any reason for that? :)

**Comment by SuperSandro2000** [comment]
I have no idea. They should just work ™️

**Comment by SuperSandro2000** [comment]
Fixed in 8666542c90cd7c05a63247f14d7369cfa206b4ca

**Comment by jerabaul29** [comment]
Looks good. A small note: I think that it will run on all commits to all branches now. If this is the expected behavior then it is fine, but if you want to run only when committing / pushing to master I think that the syntax should be something like:

```
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

etc.

Possible to change master for another branch name of course :) .
