### ISSUE TITLE
I can't use ddclient without a conf file

### ISSUE THREAD

**Issue by sixcorners** [ddclient/ddclient#78]
It would be nice if I could just put everything on the command line. It doesn't seem to work though.

    ddclient
      -file=/dev/null
      -foreground
      -daemon=300
      -syslog
      -verbose
      -debug

      -use=fw
      -fw=http://testwifi.here/api/v1/status
      -fw-skip=localIpAddress

      -ssl
      -protocol=cloudflare
      -login=sixcorners%2Bcf@example.com
      -password=CVfTw07Ii1bzq7159gQV
      -options=zone=example.com
      -host=asdf.example.com

It keeps giving me this error:

    WARNING:  skipping host: asdf.example.com: 'login=' is an invalid login.

I see that it is set correctly with the debug output:

    opt{login}                           : sixcorners%2Bcf@example.com

ddclient version 3.9.0,

**Comment by DaveSophoServices** [comment]
You're right. This is something I'd like to get fixed. I noticed it the first time I tried it too.

**Comment by stevegroom** [comment]
I am trying to do something very similar - I am running ddclient inside docker-compose and want to store the sensitive information in a local .env file and pass the login and password into the command line or config file. 
This is important as I don't want to check any secrets into my git repo.

**Comment by SuperSandro2000** [comment]
Did you try quoting the login information with single and double?

**Comment by stevegroom** [comment]
Hi @SuperSandro2000 I eventually went for a plain ```ddclient.conf``` file and added a ```.gitignore``` record. It is not ideal  because if I ever have to recreate the config file it would be a pain.

**Comment by dyennam** [comment]
Hi @stevegroom,
Could you please share how you went about with creating/defining the compose file and its required parameters.
So far i have this in my compose file (Used the following for inspiration: https://hub.docker.com/r/linuxserver/ddclient)

_cat docker-compose.yaml_ 
```yaml
---
version: "2.1"
services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - /ddns:/config
    restart: unless-stopped
```

_cat ddclient.conf_
```
#
# /etc/ddclient.conf

protocol=namecheap,
login=my_username
password='dynamic-DNS-Password-From-namecheap'
myDomain.com
```
both compose file and ddclient.conf file exist in the /ddns root directory.

When i run the compose file i am getting the following errors:
```
WARNING:  found neither ipv4 nor ipv6 address
WARNING:  unable to determine IP address
[services.d] done.
WARNING:  file /var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip' = ''
```

**Comment by stevegroom** [comment]
Hello @dyennam 
Here is my docker-compose.yml

```yaml
---
version: "2.1"
services:
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/etc/ddclient
    restart: unless-stopped

    command:  ddclient -daemon=0 -debug -verbose -noquiet
```

and config/ddclient.conf

```text
use=web
protocol=cloudflare           ##

#server=fqdn.of.api.service   ## defaults to api.cloudflare.com/client/v4
server=api.cloudflare.com/client/v4

#login                        ## login name and password  registered with the service
login=<cloudflare user email>

#password from:: My Profile -> API Tokens -> Global API Key (38 chars long)
password=<38charglobalapikeyhere>

#fully.qualified.host         ## the host registered with the service.
zone=<mydomain.com>

# This (these) are the A-records to update.
www.<mydomain.com>
```

hope this helps.

regards
Steve
